name: Update Steam Data

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Create API key file
      run: echo "${{ secrets.STEAMLADDER_API_KEY }}" > apikey.txt
    
    - name: Run data collection
      run: python topusers.py
    
    - name: Update README
      run: |
        cat > README.md << 'EOF'
        # Top Steam Accounts by Game Count
        
        This repository contains the top 20 Steam accounts ranked by number of games owned.
        
        ## Files
        
        - `steam_ids_only.txt` - Just the Steam ID 64s, one per line
        - `top_steam_accounts.json` - Full profile data
        
        ## Last Updated
        
        $(date -u)
        
        ## Note
        
        This data is collected from [SteamLadder](https://steamladder.com) and is updated automatically every Sunday.
        The Steam accounts listed are publicly available and ranked by the number of games in their library.
        
        ## Using This Data
        
        You can download the `steam_ids_only.txt` file directly:
        ```
        https://raw.githubusercontent.com/${{ github.repository }}/main/steam_ids_only.txt
        ```
        
        Or use it in your script:
        ```python
        import requests
        
        # Download the file
        url = "https://raw.githubusercontent.com/${{ github.repository }}/main/steam_ids_only.txt"
        response = requests.get(url)
        steam_ids = response.text.strip().split('\n')
        
        # Process the IDs
        for steam_id in steam_ids:
            print(f"Processing: {steam_id}")
        ```
        EOF
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add steam_ids_only.txt top_steam_accounts.json README.md
        git commit -m "Update Steam data - $(date -u)" || exit 0
        git push